module.exports = {
    "tickets": [
        {
            "url": "https://zccmujtaba.zendesk.com/api/v2/tickets/1.json",
            "id": 1,
            "external_id": null,
            "via": {
                "channel": "sample_ticket",
                "source": {
                    "from": {},
                    "to": {},
                    "rel": null
                }
            },
            "created_at": "2021-11-26T07:55:09Z",
            "updated_at": "2021-11-26T07:55:09Z",
            "type": "incident",
            "subject": "Sample ticket: Meet the ticket",
            "raw_subject": "Sample ticket: Meet the ticket",
            "description": "Hi there,\n\nI’m sending an email because I’m having a problem setting up your new product. Can you help me troubleshoot?\n\nThanks,\n The Customer\n\n",
            "priority": "normal",
            "status": "open",
            "recipient": null,
            "requester_id": 1524395610021,
            "submitter_id": 1524395598221,
            "assignee_id": 1524395598221,
            "organization_id": null,
            "group_id": 4414163541143,
            "collaborator_ids": [],
            "follower_ids": [],
            "email_cc_ids": [],
            "forum_topic_id": null,
            "problem_id": null,
            "has_incidents": false,
            "is_public": true,
            "due_at": null,
            "tags": [
                "sample",
                "support",
                "zendesk"
            ],
            "custom_fields": [],
            "satisfaction_rating": null,
            "sharing_agreement_ids": [],
            "fields": [],
            "followup_ids": [],
            "ticket_form_id": 1500003315861,
            "brand_id": 1500002349161,
            "allow_channelback": false,
            "allow_attachments": true
        },
        {
            "url": "https://zccmujtaba.zendesk.com/api/v2/tickets/2.json",
            "id": 2,
            "external_id": null,
            "via": {
                "channel": "api",
                "source": {
                    "from": {},
                    "to": {},
                    "rel": null
                }
            },
            "created_at": "2021-11-26T09:08:57Z",
            "updated_at": "2021-11-26T09:08:57Z",
            "type": null,
            "subject": "velit eiusmod reprehenderit officia cupidatat",
            "raw_subject": "velit eiusmod reprehenderit officia cupidatat",
            "description": "Aute ex sunt culpa ex ea esse sint cupidatat aliqua ex consequat sit reprehenderit. Velit labore proident quis culpa ad duis adipisicing laboris voluptate velit incididunt minim consequat nulla. Laboris adipisicing reprehenderit minim tempor officia ullamco occaecat ut laborum.\n\nAliquip velit adipisicing exercitation irure aliqua qui. Commodo eu laborum cillum nostrud eu. Mollit duis qui non ea deserunt est est et officia ut excepteur Lorem pariatur deserunt.",
            "priority": null,
            "status": "open",
            "recipient": null,
            "requester_id": 1524395598221,
            "submitter_id": 1524395598221,
            "assignee_id": 1524395598221,
            "organization_id": 1500635770741,
            "group_id": 4414163541143,
            "collaborator_ids": [],
            "follower_ids": [],
            "email_cc_ids": [],
            "forum_topic_id": null,
            "problem_id": null,
            "has_incidents": false,
            "is_public": true,
            "due_at": null,
            "tags": [
                "est",
                "incididunt",
                "nisi"
            ],
            "custom_fields": [],
            "satisfaction_rating": null,
            "sharing_agreement_ids": [],
            "fields": [],
            "followup_ids": [],
            "ticket_form_id": 1500003315861,
            "brand_id": 1500002349161,
            "allow_channelback": false,
            "allow_attachments": true
        },
        {
            "url": "https://zccmujtaba.zendesk.com/api/v2/tickets/3.json",
            "id": 3,
            "external_id": null,
            "via": {
                "channel": "api",
                "source": {
                    "from": {},
                    "to": {},
                    "rel": null
                }
            },
            "created_at": "2021-11-26T10:54:39Z",
            "updated_at": "2021-11-26T10:54:39Z",
            "type": null,
            "subject": "velit eiusmod reprehenderit officia cupidatat",
            "raw_subject": "velit eiusmod reprehenderit officia cupidatat",
            "description": "Aute ex sunt culpa ex ea esse sint cupidatat aliqua ex consequat sit reprehenderit. Velit labore proident quis culpa ad duis adipisicing laboris voluptate velit incididunt minim consequat nulla. Laboris adipisicing reprehenderit minim tempor officia ullamco occaecat ut laborum.\n\nAliquip velit adipisicing exercitation irure aliqua qui. Commodo eu laborum cillum nostrud eu. Mollit duis qui non ea deserunt est est et officia ut excepteur Lorem pariatur deserunt.",
            "priority": null,
            "status": "open",
            "recipient": null,
            "requester_id": 1524395598221,
            "submitter_id": 1524395598221,
            "assignee_id": 1524395598221,
            "organization_id": 1500635770741,
            "group_id": 4414163541143,
            "collaborator_ids": [],
            "follower_ids": [],
            "email_cc_ids": [],
            "forum_topic_id": null,
            "problem_id": null,
            "has_incidents": false,
            "is_public": true,
            "due_at": null,
            "tags": [
                "est",
                "incididunt",
                "nisi"
            ],
            "custom_fields": [],
            "satisfaction_rating": null,
            "sharing_agreement_ids": [],
            "fields": [],
            "followup_ids": [],
            "ticket_form_id": 1500003315861,
            "brand_id": 1500002349161,
            "allow_channelback": false,
            "allow_attachments": true
        }
    ],
    "next_page": null,
    "previous_page": null,
    "count": 3
}